version: "3.8"
services:
  # redis:
    # image: redis
    # ports:
      # - "6379"
    # networks:
      # - frontend
    # deploy:
      # replicas: 2
      # update_config:
        # parallelism: 2
        # delay: 10s
      # restart_policy:
        # condition: on-failure

  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    networks:
      - frontend
    volumes:
      - grafana-storage:/var/lib/grafana

  meerschaum_db:
    environment:
      - TIMESCALEDB_TELEMETRY=off
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    image: "timescale/timescaledb:${TIMESCALEDB_VERSION}"
    ports:
      - "5432:5432"
    volumes:
      - meerschaum_db_data:/var/lib/postgresql/data
    networks:
      - backend
    # deploy:
      # placement:
        # max_replicas_per_node: 1
        # constraints:
          # - "node.role==manager"

networks:
  frontend:
  backend:

volumes:
  meerschaum_db_data:
  grafana-storage:
